package cli

import (
	"bytes"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"

	"github.com/myfoxit/goforge/templates"
)

// ScaffoldData feeds the app templates.
type ScaffoldData struct {
	Name           string
	Module         string
	DB             string
	Modules        []string
	GoForgeVersion string
	// LocalFramework, when non-empty, adds a `replace` directive pointing at
	// a local framework checkout (development mode).
	LocalFramework string
	UI             bool
	// Template is the scaffold flavor (minimal|demo|saas). It selects which
	// _variants/<Template> frontend overlay is rendered.
	Template string
}

// variantMarker names the directory whose immediate children are per-template
// overlays: templates/app/ui/src/_variants/<template>/... maps onto
// templates/app/ui/src/... for the matching template and is pruned otherwise.
const variantMarker = "_variants"

// resolveVariant maps a scaffold-relative path through the _variants overlay.
// It returns the rewritten path (with the _variants/<template> prefix removed)
// and whether the path belongs to a different template and should be skipped.
func resolveVariant(rel, template string) (string, bool) {
	parts := strings.Split(rel, "/")
	for i, p := range parts {
		if p != variantMarker {
			continue
		}
		if i+1 >= len(parts) {
			// the marker directory itself — collapse it, keep descending
			return strings.Join(append(parts[:i:i], parts[i+1:]...), "/"), false
		}
		if parts[i+1] != template {
			return "", true // a different template's overlay — prune it
		}
		return strings.Join(append(parts[:i:i], parts[i+2:]...), "/"), false
	}
	return rel, false
}

// RenderScaffold writes the app template into targetDir.
func RenderScaffold(targetDir string, data ScaffoldData) error {
	return fs.WalkDir(templates.FS, templates.AppRoot, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel := strings.TrimPrefix(path, templates.AppRoot)
		rel = strings.TrimPrefix(rel, "/")
		if rel == "" {
			return nil
		}
		// Skip the ui tree and its embed glue for API-only apps.
		if !data.UI && (rel == "ui" || strings.HasPrefix(rel, "ui/") || rel == "app_ui.go.tmpl") {
			if d.IsDir() {
				return fs.SkipDir
			}
			return nil
		}
		// Resolve the per-template frontend overlay: keep this template's
		// _variants subtree (rewriting the path) and prune the others.
		mapped, skip := resolveVariant(rel, data.Template)
		if skip {
			if d.IsDir() {
				return fs.SkipDir
			}
			return nil
		}
		rel = mapped
		if rel == "" {
			return nil
		}
		target := filepath.Join(targetDir, rel)
		if d.IsDir() {
			return os.MkdirAll(target, 0o755)
		}

		raw, err := templates.FS.ReadFile(path)
		if err != nil {
			return err
		}
		if strings.HasSuffix(rel, ".tmpl") {
			target = strings.TrimSuffix(target, ".tmpl")
			rendered, err := renderTemplate(rel, string(raw), data)
			if err != nil {
				return err
			}
			// A template that renders to nothing (e.g. fully guarded by a
			// {{if}} that didn't fire) produces no file.
			if len(bytes.TrimSpace(rendered)) == 0 {
				return nil
			}
			raw = rendered
		}
		// "dot-" prefix works around tooling that ignores dotfiles in embeds.
		base := filepath.Base(target)
		if strings.HasPrefix(base, "dot-") {
			target = filepath.Join(filepath.Dir(target), "."+strings.TrimPrefix(base, "dot-"))
		}
		if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
			return err
		}
		return os.WriteFile(target, raw, 0o644)
	})
}

func renderTemplate(name, src string, data ScaffoldData) ([]byte, error) {
	t, err := template.New(name).Funcs(template.FuncMap{
		"hasModule": func(id string) bool {
			for _, m := range data.Modules {
				if m == id {
					return true
				}
			}
			return false
		},
	}).Parse(src)
	if err != nil {
		return nil, fmt.Errorf("template %s: %w", name, err)
	}
	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("render %s: %w", name, err)
	}
	return buf.Bytes(), nil
}

// GenerateModulesFile writes modules_gen.go wiring the selected modules.
func GenerateModulesFile(appDir string, moduleIDs []string) error {
	byID := CatalogByID()
	imports := map[string]string{} // import path → alias ("" = default)
	var exprs []string
	for _, id := range moduleIDs {
		def, ok := byID[id]
		if !ok {
			return fmt.Errorf("unknown module %q", id)
		}
		imports["github.com/myfoxit/goforge/"+def.Import] = ""
		exprs = append(exprs, def.Expr)
	}

	paths := make([]string, 0, len(imports))
	for p := range imports {
		paths = append(paths, p)
	}
	sort.Strings(paths)

	var b bytes.Buffer
	b.WriteString("// Code generated by forge; DO NOT EDIT.\n")
	b.WriteString("// Regenerate with: forge add / forge remove\n\n")
	b.WriteString("package main\n\nimport (\n")
	b.WriteString("\tforge \"github.com/myfoxit/goforge\"\n")
	for _, p := range paths {
		fmt.Fprintf(&b, "\t\"%s\"\n", p)
	}
	b.WriteString(")\n\n")
	b.WriteString("// forgeModules returns the modules enabled in forge.json.\n")
	b.WriteString("func forgeModules() []forge.Module {\n\treturn []forge.Module{\n")
	for _, e := range exprs {
		fmt.Fprintf(&b, "\t\t%s,\n", e)
	}
	b.WriteString("\t}\n}\n")
	return os.WriteFile(filepath.Join(appDir, "modules_gen.go"), b.Bytes(), 0o644)
}
